services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - app-network

  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - embeddings_service
    environment:
      - EMBEDDINGS_SERVICE_URL=http://embeddings_service:8001
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    networks:
      - app-network

  embeddings_service:
    build: ./embeddings_service
    container_name: embeddings_service
    ports:
      - "8001:8001"
    networks:
      - app-network

volumes:
  qdrant_storage:

networks:
  app-network:
    driver: bridge
